### ISSUE TITLE
peg::parse_error escapes parse()

### ISSUE THREAD

**Issue by sasq64** [yhirose/cpp-peglib#119]
I explicitly throw peg::parse_error() in some actions, and it can happen that this exception is not caught in peglib. This is a stactrace:

```
#0  0x00007ffff7e49762 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000661cd1 in ParserWrapper::action(char const*, std::function<std::any (SVWrap const&)> const&) const::$_1::operator()(peg::SemanticValues const&) const (this=<optimized out>, sv=...)
    at /home/sasq/projects/badass/src/wrap.cpp:143
#2  0x0000000000661ebc in std::_Function_handler<std::any (peg::SemanticValues const&), ParserWrapper::action(char const*, std::function<std::any (SVWrap const&)> const&) const::$_1>::_M_invoke(std::_Any_data const&, peg::SemanticValues const&) (__functor=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:285
#3  0x0000000000760d11 in std::function<std::any (peg::SemanticValues const&)>::operator()(peg::SemanticValues const&) const (this=0x7fffffff5000, __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#4  peg::call<std::any, std::function<std::any (peg::SemanticValues const&)>, (decltype(nullptr))0, peg::SemanticValues&>(std::function<std::any (peg::SemanticValues const&)>, peg::SemanticValues&) (fn=..., 
    args=...) at /home/sasq/projects/badass/external/peglib/peglib.h:621
#5  peg::Action::TypeAdaptor_csv<std::any>::operator() (this=<optimized out>, sv=...)
    at /home/sasq/projects/badass/external/peglib/peglib.h:691
#6  0x000000000076098c in std::_Function_handler<std::any (peg::SemanticValues&, std::any&), peg::Action::TypeAdaptor_csv<std::any> >::_M_invoke(std::_Any_data const&, peg::SemanticValues&, std::any&) (
    __functor=..., __args=std::any [no contained value], __args=std::any [no contained value])
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:285
#7  0x0000000000699a72 in std::function<std::any (peg::SemanticValues&, std::any&)>::operator()(peg::SemanticValues&, std::any&) const (this=0x7ffff7e49780 <__cxa_throw+48>, 
    __args=std::any [no contained value], __args=std::any [no contained value])
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#8  peg::Action::operator() (this=0x7ffff7e49780 <__cxa_throw+48>, sv=..., 
    dt=std::any [no contained value]) at /home/sasq/projects/badass/external/peglib/peglib.h:677
#9  peg::PrecedenceClimbing::parse_expression (this=0x60b0000005d0, s=<optimized out>, 
    n=<optimized out>, sv=..., c=..., dt=..., min_prec=<optimized out>)
    at /home/sasq/projects/badass/external/peglib/peglib.h:2686
#10 0x0000000000678dee in peg::PrecedenceClimbing::parse_core (this=0x60e000001860, 
    s=0x991918 <typeinfo for peg::parse_error> "\240A\242", n=7737008, sv=..., c=..., 
    dt=<error reading variable: Cannot access memory at address 0x0>...)
    at /home/sasq/projects/badass/external/peglib/peglib.h:1546
#11 0x000000000066428c in peg::Ope::parse (this=<optimized out>, s=<optimized out>, n=<optimized out>, 
    sv=..., c=..., dt=...) at /home/sasq/projects/badass/external/peglib/peglib.h:2422
#12 0x00000000006a2558 in peg::Holder::parse_core(char const*, unsigned long, peg::SemanticValues&, peg::Context&, std::any&) const::{lambda(std::any&)#1}::operator()(std::any&) const (this=<optimized out>, 
    a_val=...) at /home/sasq/projects/badass/external/peglib/peglib.h:2489
#13 0x0000000000665aa4 in peg::Context::packrat<peg::Holder::parse_core(char const*, unsigned long, peg::SemanticValues&, peg::Context&, std::any&) const::{lambda(std::any&)#1}>(char const*, unsigned long, unsigned long&, std::any&, peg::Holder::parse_core(char const*, unsigned long, peg::SemanticValues&, peg::Context&, std::any&) const::{lambda(std::any&)#1}) (this=0x7fffffffba20, a_s=<optimized out>, 
    def_id=10, len=<optimized out>, val=..., fn=...)
    at /home/sasq/projects/badass/external/peglib/peglib.h:897
...
```
Throwing in this action causes the program to exit with uncaught exception:
`terminate called after throwing an instance of 'peg::parse_error'`

**Comment by yhirose** [comment]
@sasq64, thanks for the report. Could you show the smallest possible code example to reproduce the problem?

At least in my two unit cases using `peg::parse_error()` don't have any problem. One of the is as bellow:
https://github.com/yhirose/cpp-peglib/blob/14305f9f53cde207568f21675a1b9294a3ab28b4/test/test2.cc#L654-L676

**Comment by sasq64** [comment]
It was from fuzzing input. I'll see if I can simplify it tomorrow.
But looks like it may happen when I throw from the an action on an operator in precedence climbing (+packrat)

**Comment by yhirose** [comment]
@sasq64, I still don't know how to reproduce it on my machine. Could you give me the smallest possible code snippet to reproduce it, otherwise I'll close it for now? Thanks!
